### ISSUE TITLE
continuous url fetching

### ISSUE THREAD

**Issue by muralikodali** [Phantas0s/gocket#1]
url fetching process is continuous without stop, when i issued the following command in terminal.

```
gocket list -c 20 -t | sed 'N;s#\n# /// #' | fzf | awk -F ' /// ' '{print $2}' | xargs w3m 
or
gocket list -c 20 -t | sed 'N;s#\n# /// #' | fzf | awk -F ' /// ' '{print $2}' | xargs firefox

```

gocket list -c 20 is fetchng urls list without any problem.

I request you to give browser option in configuration file ( to set terminal browsers like w3m ) as interface of terminal browser goes well with gocket tui and change over to view mode is quick.

w3m with [readerview](https://github.com/eafer/rdrview) gives distraction free reading experience.

**Comment by Phantas0s** [comment]
I didn't know readerview, looks pretty cool. Thanks for that!

That's a good idea to be able to specify the browser in the config. I'll add that to my list.

For your problem it should be fixed with the new version (v0.2.2). If it is, thanks to close the ticket :)

**Comment by muralikodali** [comment]
still the p

**Comment by muralikodali** [comment]
still the problem is not solved with new version.

screenshot attached showing the terminal.

![screenshot_20210310174421](https://user-images.githubusercontent.com/11482766/110627682-466e2d00-81c8-11eb-90d6-2137951a9790.png)

**Comment by Phantas0s** [comment]
I need to know more to try to debug the problem:

1. What's the exact commands which don't work for you?
2. What do you mean by URL fetching process is not stopping? Can you move in the list or is it totally blocked?

**Comment by muralikodali** [comment]
I have attached a gif file to show the exact problem.

I have tried to stop the program with Ctrl+c , in the end.

![gocket](https://user-images.githubusercontent.com/11482766/110757370-5261f980-8271-11eb-951c-a7e1c4ad48a1.gif)

**Comment by Phantas0s** [comment]
Oh I think I got it. It's because you have in your config `tui: true` and you try to use fzf to display the list. You can't use both at the same time.

Try `gocket list -c 5 -t --tui=false | sed 'N;s#\n# /// #' | fzf | awk -F ' /// ' '{print $2}' | xargs firefox`

You need to have fzf for this command to work.

**Comment by muralikodali** [comment]
Thanks

putting --tui=false does the trick.

closing the program is not smooth, when we try to abort the process while selecting the url. if we abort at the time of selecting the url, it is showing stream closed error and we have to again press ctrl+q one or two times.

**Comment by Phantas0s** [comment]
I don't have this problem. Send me a gif? :D

This kind of stuff depends on your terminal, the shell you're using, and what processes are running.

**Comment by muralikodali** [comment]
My OS i s Arch LInux. terminal is alacritty and shell is fish.

![gocket3](https://user-images.githubusercontent.com/11482766/110818482-4bf47180-82b3-11eb-9e3f-cf7024c7096d.gif)

**Comment by Phantas0s** [comment]
It's not from gocket. When you cancel, fzf sends to w3m some whitespace and w3m tries to open it.

Since your initial problem is solved I close the issue.

**Comment by Phantas0s** [comment]
It's not from gocket. When you cancel, fzf sends to w3m some whitespace and w3m tries to open it.

Since your initial problem is solved I close the issue.
