### ISSUE TITLE
Wrong URL opened

### ISSUE THREAD

**Issue by focusaurus** [Phantas0s/gocket#2]
I had the top article highlighted and typed ENTER and the bottom URL opened.

![gocket-wrong-url-11-13-38](https://user-images.githubusercontent.com/482377/110518069-e2b10a80-80c8-11eb-812c-1b7e1bfd8c7c.png)

**Comment by Phantas0s** [comment]
That's a problem indeed :smile: 

It's fixed now (v0.2.2). If it works for you, thanks to close the ticket :+1:

**Comment by focusaurus** [comment]
Confirmed fix. Thanks!
