### ISSUE TITLE
Authorization issue with Pocket on Windows

### ISSUE THREAD

**Issue by jrhawley** [Phantas0s/gocket#4]
Hi there,

Thanks for making this tool, this is great! I always like seeing new TUI clients for online services.

# Issue

I'm trying to run gocket from Powershell in Windows Terminal on Windows 10. I've built the binary from source and followed the authorization instructions in the README and saved the application key in `C:\Users\<user>\AppData\Local\gocket\config.yml`.

However, when I run `gocket list`, a new webpage opens to authorize the application with Pocket for the first time, and the application doesn't authorize.

![image](https://user-images.githubusercontent.com/6157112/113016251-4ec4e280-914c-11eb-92d0-db9a2f9e2f8a.png)

There isn't any more specific information than this, so I'm not sure where the issue might be.

# Troubleshooting

## Gocket does run properly within Windows Subsystem for Linux

Using the Windows Subsystem for Linux, I've built the binary again in my Ubuntu subsystem and copied the `config.yml` file from `C:\Users\<user>\AppData\Local\gocket\config.yml`. to `/home/<user>/.config/gocket/config.yml`. When I run `gocket list`, the app authorizes correctly and I can see my saved list.

So I think I've made the application key correctly and stored it in the right format.

## Console error message

On Windows, when the authorization step fails, there are a couple errors listed in the Firefox console that may help with diagnosing the issue.

![image](https://user-images.githubusercontent.com/6157112/113014684-cc87ee80-914a-11eb-8bdf-a02f50bef238.png)

On Microsoft Edge (Chromium version), the console error is similar but slightly different.

![image](https://user-images.githubusercontent.com/6157112/113015928-fdb4ee80-914b-11eb-810a-d2e36d9fd3ee.png)

# Machine information

Just in case this will help, here is some information about my system.

| Variable | Value |
| --------- | ------ |
| Operating system | Windows 10 Pro version 20H2 x86_64 |
| Kernel | Kernel: 10.0.19042 |
| Browser | Firefox 87.0, Edge 89.0.774.63 |

Thanks

**Comment by Phantas0s** [comment]
Hello!

Thanks for the detailed issue. It helped a lot to find the bug.

It should be fixed now; you can get the last version (0.2.4) and try on your system. If it's good for you, don't forget to close the issue.

If you have any feedback or question, don't hesitate to create another one :)

**Comment by jrhawley** [comment]
That's great, I'm glad it was helpful.

Everything seems to be working now.
I pulled the latest versions from the repo, ran `go install`, and everything was authorized correctly.
Thanks for fixing the issue!
